/* GENERATED FILE — DO NOT EDIT MANUALLY
 * Source contracts: shared/contracts/ and shared/constants/
 * Generated by: node shared/generate-contract-adapters.mjs
 */

export const API_PATHS = {
  "client": {
    "getRequests": "/client/requests",
    "submitRequest": "/client/requests",
    "getPets": "/client/pets",
    "updatePet": "/client/pets/{petId}",
    "requestCancellation": "/client/cancel"
  },
  "admin": {
    "getRequests": "/admin/requests",
    "getRequest": "/admin/requests/{requestId}",
    "postAction": "/admin/requests",
    "review": "/admin/review",
    "assign": "/admin/assign",
    "jobStart": "/admin/job/start",
    "jobComplete": "/admin/job/complete",
    "getPets": "/admin/pets",
    "getPetById": "/admin/pets/{petId}",
    "createPet": "/admin/pets",
    "updatePet": "/admin/pets/{petId}",
    "getStaff": "/admin/staff",
    "getClients": "/admin/clients",
    "cancelDecision": "/admin/cancel/decision",
    "exportData": "/admin/export-data",
    "tenantInfo": "/admin/tenant-info"
  },
  "public": {
    "submitRequest": "/requests",
    "staffOptions": "/requests"
  }
} as const;
export const PET_FIELDS = {
  "clientReadFields": [
    "pet_id",
    "name",
    "species",
    "breed",
    "age",
    "care_instructions",
    "feeding_notes",
    "medication_notes",
    "behavior_notes",
    "is_active"
  ],
  "clientWriteFields": [
    "name",
    "species",
    "breed",
    "age",
    "care_instructions",
    "feeding_notes",
    "medication_notes",
    "behavior_notes",
    "health"
  ],
  "clientWriteHealthSubfields": [
    "vet_name",
    "vet_phone"
  ],
  "clientWriteHealthFieldLimits": {
    "vet_name": 100,
    "vet_phone": 100
  },
  "fieldLimits": {
    "name": 100,
    "species": 100,
    "breed": 100,
    "age": 100,
    "care_instructions": 2000,
    "feeding_notes": 2000,
    "medication_notes": 2000,
    "behavior_notes": 2000
  },
  "clientPetEditApiAvailability": "pending-phase-1B5C-A-deployment"
} as const;
export const REQUEST_STATUSES = {
  "statuses": {
    "PENDING_REVIEW": {
      "label": "Pending Review",
      "category": "neutral",
      "terminal": false,
      "customerVisible": true,
      "staffSettable": false,
      "synonyms": [
        "NEEDS_REVIEW"
      ]
    },
    "MEET_GREET_REQUIRED": {
      "label": "Meet & Greet Required",
      "category": "informational",
      "terminal": false,
      "customerVisible": false,
      "staffSettable": true,
      "synonyms": [
        "NEEDS_MG"
      ]
    },
    "MG_SCHEDULED": {
      "label": "Meet & Greet Scheduled",
      "category": "informational",
      "terminal": false,
      "customerVisible": false,
      "staffSettable": true,
      "synonyms": []
    },
    "MG_COMPLETED": {
      "label": "Meet & Greet Completed",
      "category": "informational",
      "terminal": false,
      "customerVisible": false,
      "staffSettable": true,
      "synonyms": []
    },
    "PROFILE_CREATED": {
      "label": "Profile Created",
      "category": "informational",
      "terminal": false,
      "customerVisible": false,
      "staffSettable": true,
      "synonyms": []
    },
    "READY_FOR_APPROVAL": {
      "label": "Ready for Approval",
      "category": "informational",
      "terminal": false,
      "customerVisible": false,
      "staffSettable": true,
      "synonyms": [
        "NEW_REQUEST"
      ]
    },
    "QUOTE_NEEDED": {
      "label": "Quote Needed",
      "category": "informational",
      "terminal": false,
      "customerVisible": false,
      "staffSettable": true,
      "synonyms": []
    },
    "QUOTE_SENT": {
      "label": "Quote Sent",
      "category": "informational",
      "terminal": false,
      "customerVisible": true,
      "staffSettable": true,
      "synonyms": [
        "QUOTED"
      ]
    },
    "APPROVED": {
      "label": "Approved",
      "category": "success",
      "terminal": false,
      "customerVisible": true,
      "staffSettable": true,
      "synonyms": [
        "BOOKED"
      ]
    },
    "ASSIGNED": {
      "label": "Assigned",
      "category": "success",
      "terminal": false,
      "customerVisible": true,
      "staffSettable": true,
      "synonyms": [
        "JOB_CREATED",
        "SCHEDULED"
      ]
    },
    "DECLINED": {
      "label": "Declined",
      "category": "danger",
      "terminal": true,
      "customerVisible": true,
      "staffSettable": true,
      "synonyms": []
    },
    "CANCELLATION_REQUESTED": {
      "label": "Cancellation Requested",
      "category": "warning",
      "terminal": false,
      "customerVisible": true,
      "staffSettable": false,
      "synonyms": []
    },
    "CANCELLATION_DENIED": {
      "label": "Cancellation Denied",
      "category": "warning",
      "terminal": false,
      "customerVisible": true,
      "staffSettable": true,
      "synonyms": []
    },
    "CANCELLED": {
      "label": "Cancelled",
      "category": "danger",
      "terminal": true,
      "customerVisible": true,
      "staffSettable": true,
      "synonyms": []
    },
    "COMPLETED": {
      "label": "Completed",
      "category": "success",
      "terminal": true,
      "customerVisible": true,
      "staffSettable": true,
      "synonyms": []
    },
    "ARCHIVED": {
      "label": "Archived",
      "category": "neutral",
      "terminal": true,
      "customerVisible": false,
      "staffSettable": true,
      "synonyms": []
    },
    "DELETED": {
      "label": "Deleted",
      "category": "neutral",
      "terminal": true,
      "customerVisible": false,
      "staffSettable": true,
      "synonyms": []
    }
  },
  "categories": [
    "neutral",
    "informational",
    "success",
    "warning",
    "danger"
  ]
} as const;
export const SERVICE_TYPES = {
  "services": {
    "WALK_30MIN": {
      "label": "30-Min Walk",
      "labelLong": "30-Minute Walk",
      "durationMinutes": 30,
      "availableInIntake": true,
      "supportedOnMobile": true
    },
    "WALK_60MIN": {
      "label": "60-Min Walk",
      "labelLong": "60-Minute Walk",
      "durationMinutes": 60,
      "availableInIntake": true,
      "supportedOnMobile": true
    },
    "DROPIN_1HR": {
      "label": "1-Hour Drop-in",
      "labelLong": "1-Hour Drop-in",
      "durationMinutes": 60,
      "availableInIntake": true,
      "supportedOnMobile": true
    },
    "DROPIN_3HR": {
      "label": "3-Hour Drop-in",
      "labelLong": "3-Hour Drop-in",
      "durationMinutes": 180,
      "availableInIntake": true,
      "supportedOnMobile": true
    },
    "OVERNIGHT": {
      "label": "Overnight Care",
      "labelLong": "Overnight Care",
      "durationMinutes": 720,
      "availableInIntake": true,
      "supportedOnMobile": true
    },
    "PET_SITTING": {
      "label": "Pet Sitting",
      "labelLong": "Pet Sitting",
      "durationMinutes": 60,
      "availableInIntake": true,
      "supportedOnMobile": true
    },
    "MEET_GREET": {
      "label": "Meet & Greet",
      "labelLong": "Meet & Greet",
      "durationMinutes": 45,
      "availableInIntake": false,
      "supportedOnMobile": true
    }
  }
} as const;

/**
 * Safe path builder helper for parameterized route templates (e.g., '/client/pets/{petId}').
 * Replaces placeholders like '{petId}' with encodeURIComponent(value).
 */
export function buildPath(template: string, params: Record<string, string | number> = {}): string {
  if (!template || typeof template !== 'string') {
    throw new Error('buildPath requires a valid string template');
  }
  return template.replace(/\{([^}]+)\}/g, (match, paramName) => {
    const value = params[paramName];
    if (value === undefined || value === null || value === '') {
      throw new Error(`Missing required path parameter: ${paramName}`);
    }
    return encodeURIComponent(String(value));
  });
}
