# GENERATED FILE — DO NOT EDIT MANUALLY
# Source contract: shared/constants/service-types.json
# Generated by: node shared/generate-contract-adapters.mjs

SERVICE_TYPES = {
    "services": {
        "WALK_30MIN": {
            "label": "30-Min Walk",
            "labelLong": "30-Minute Walk",
            "durationMinutes": 30,
            "availableInIntake": True,
            "supportedOnMobile": True,
        },
        "WALK_60MIN": {
            "label": "60-Min Walk",
            "labelLong": "60-Minute Walk",
            "durationMinutes": 60,
            "availableInIntake": True,
            "supportedOnMobile": True,
        },
        "DROPIN_1HR": {
            "label": "1-Hour Drop-in",
            "labelLong": "1-Hour Drop-in",
            "durationMinutes": 60,
            "availableInIntake": True,
            "supportedOnMobile": True,
        },
        "DROPIN_3HR": {
            "label": "3-Hour Drop-in",
            "labelLong": "3-Hour Drop-in",
            "durationMinutes": 180,
            "availableInIntake": True,
            "supportedOnMobile": True,
        },
        "OVERNIGHT": {
            "label": "Overnight Care",
            "labelLong": "Overnight Care",
            "durationMinutes": 720,
            "availableInIntake": True,
            "supportedOnMobile": True,
        },
        "PET_SITTING": {
            "label": "Pet Sitting",
            "labelLong": "Pet Sitting",
            "durationMinutes": 60,
            "availableInIntake": True,
            "supportedOnMobile": True,
        },
        "MEET_GREET": {
            "label": "Meet & Greet",
            "labelLong": "Meet & Greet",
            "durationMinutes": 45,
            "availableInIntake": False,
            "supportedOnMobile": True,
        },
    },
}
